### ISSUE TITLE
Add QT support?

### ISSUE THREAD

**Issue by belldandu** [wxMEdit/wxMEdit#136]
I don't know about some people but most people prefer QT over GTK. Any plans to implement this so that i don't have to look at gnome like interface on my QT arch linux.

**Comment by hltj** [comment]
It may be possible in future, while I can say anything about the plan for it seems not easy.

**Comment by Neonking** [comment]
Hello @belldandu ,
Thank you for using wxMEDit . After some googling i felt on [That](https://wiki.archlinux.org/index.php/Uniform_look_for_Qt_and_GTK_applications) you might find interesting if you didn't knew about . Also, Note that wxMEdit isn't based on GTK itself ,but on wxwidgets wich has already [experimental Qt Support](https://github.com/wxWidgets/wxWidgets/tree/master/src/qt) if you feel like recompiling wxWidgets from sources for such purposes. GTK+ is just the default renderer for wxWidgets.
Otherwise Qt native-use would require complete rewrite of the application which would be long and painful and a bit pointless regarding the current state of development. If you really want to be full Qt within wxMEdit you should try to go further on wxWidgets Qt support originally written by @seandepagnier
Best Regards,
Jerome
